//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertTriggerNodeOperator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlertTriggerNodeOperator()
        {
            this.AlertTriggerNodes = new HashSet<AlertTriggerNode>();
        }
    
        public int Id { get; set; }
        public int AlertTriggerNodeTypeId { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public string DotNetProperty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertTriggerNode> AlertTriggerNodes { get; set; }
        public virtual AlertTriggerNodeType AlertTriggerNodeType { get; set; }
    }
}
