//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertTriggerNode
    {
        public int Id { get; set; }
        public Nullable<int> AlertTriggerNodeOperatorId { get; set; }
        public string DynamicNodeValue { get; set; }
        public string DynamicNodeDotNetDataType { get; set; }
        public int PositionInGroup { get; set; }
        public int AlertTriggerGroupId { get; set; }
    
        public virtual AlertTriggerGroup AlertTriggerGroup { get; set; }
        public virtual AlertTriggerNodeOperator AlertTriggerNodeOperator { get; set; }
    }
}
