//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardMetadata
    {
        public int Id { get; set; }
        public string MetadataItemName { get; set; }
        public string MetadataItemValue { get; set; }
        public string MetadataItemDotNetType { get; set; }
        public System.DateTime TimeAdded { get; set; }
    }
}
