//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int Id { get; set; }
        public Nullable<int> AlertTriggerGroupId { get; set; }
        public int AlertTypeId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PublishingSystemId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AlertTriggerGroup AlertTriggerGroup { get; set; }
        public virtual AlertType AlertType { get; set; }
        public virtual PublishingSystem PublishingSystem { get; set; }
        public virtual CLSUser CLSUser { get; set; }
    }
}
