//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLS.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int Id { get; set; }
        public int AlertTriggerGroupId { get; set; }
        public int AlertTypeId { get; set; }
        public string UserId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateTimeEnabled { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AlertTriggerGroup AlertTriggerGroup { get; set; }
        public virtual AlertType AlertType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
